# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Finde dein Haustier | Suche nach verlorenen Haustieren mit hilfe von Werbung auf Sozialen Netzwerken
description: Wir helfen Menschen, ihre vermissten Haustiere mit Anzeigen in sozialen Netzwerken zu finden. Innerhalb weniger Stunden informieren wir tausende Menschen in dem Gebiet, in welchem sich das Tier befindet.
author: palmmedia.co
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://findedeinhaustier.de/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
sass:
    style: compressed

#plugins:
#  - jekyll-autoprefixer
